# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
safe:         true
include:      [".htaccess"]
exclude:      []
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:        null
limit_posts:        0
future:             true
unpublished:        false

# Dependencies
markdown:           redcarpet
highlighter:        true

# Permalinks
# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink:              pretty
relative_permalinks:    true

# Setup
title:              Ruff Portal
tagline:            'Ruff Portal'
description:        'Automation and management system for dog rescues.'
url:                https://dallaspetsalive.github.io/ruff-portal
baseurl:            /ruff-portal

# Name of your blog (this will show up at the top of your page)
author:             'DallasPetsAlive'
name:               'DallasPetsAlive'
url:                https://github.com/DallasPetsAlive

# How many articles do you wish to appear on the front page:
paginate:           3

# Exclude metadata and development time dependencies
exclude: [LICENSE, README.md, package.json, grunt.js, Gruntfile.js, node_modules, src]

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
# baseurl:


